 // Mock data for demonstration
export const mockUsers = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah@example.com",
    role: "client",
    avatar: "/fit-woman-outdoors.png",
    phone: "+1 (555) 010-1234",
    bio: "Dedicated client focused on cardio and strength training. Regularly attends HIIT and Strength classes.",
  },
  {
    id: "2",
    name: "Mike Chen",
    email: "mike@example.com",
    role: "trainer",
    avatar: "/man-trainer.jpg",
    phone: "+1 (555) 020-5678",
    bio: "Certified strength and conditioning coach with 8 years experience training small groups and athletes.",
    certifications: ["NASM-CPT", "CPR/AED"],
    experienceYears: 8,
  },
  {
    id: "3",
    name: "Emily Davis",
    email: "emily@example.com",
    role: "client",
    avatar: "/woman-athletic.jpg",
  },
  {
    id: "4",
    name: "Alex Rivera",
    email: "alex@example.com",
    role: "trainer",
    avatar: "/trainer-professional.jpg",
  },
]

export const mockCourses = [
  {
    id: "1",
    title: "HIIT Fundamentals",
    description: "High-intensity interval training designed to boost your cardio and build strength",
    trainer: "Mike Chen",
    trainerId: "2",
    duration: "6 weeks",
    difficulty: "Intermediate",
    maxCapacity: 15,
    currentEnrollment: 12,
    schedule: "Mon & Wed, 6:00 PM",
    objectives: ["Improve cardiovascular endurance", "Build lean muscle", "Increase metabolic rate"],
    image: "/hiit-training.png",
  },
  {
    id: "2",
    title: "Yoga for Beginners",
    description: "Learn the basics of yoga with focus on flexibility, balance, and mindfulness",
    trainer: "Alex Rivera",
    trainerId: "4",
    duration: "8 weeks",
    difficulty: "Beginner",
    maxCapacity: 20,
    currentEnrollment: 18,
    schedule: "Tue & Thu, 7:00 AM",
    objectives: ["Master foundational poses", "Improve flexibility", "Develop breathing techniques"],
    image: "/diverse-yoga-class.png",
  },
  {
    id: "3",
    title: "Strength & Conditioning",
    description: "Advanced strength training program for building muscle and power",
    trainer: "Mike Chen",
    trainerId: "2",
    duration: "10 weeks",
    difficulty: "Advanced",
    maxCapacity: 12,
    currentEnrollment: 10,
    schedule: "Mon, Wed & Fri, 5:00 PM",
    objectives: ["Increase maximum strength", "Improve power output", "Perfect lifting technique"],
    image: "/strength-training-diverse-group.png",
  },
  {
    id: "4",
    title: "Pilates Core Strength",
    description: "Focus on core stability and controlled movements for total body conditioning",
    trainer: "Alex Rivera",
    trainerId: "4",
    duration: "6 weeks",
    difficulty: "Intermediate",
    maxCapacity: 15,
    currentEnrollment: 14,
    schedule: "Tue & Thu, 6:00 PM",
    objectives: ["Strengthen core muscles", "Improve posture", "Enhance body awareness"],
    image: "/pilates-class.png",
  },
]

export const mockSessions = [
  {
    id: "1",
    courseId: "1",
    date: "2025-01-15",
    time: "6:00 PM",
    exercises: ["Burpees", "Jump Squats", "Mountain Climbers", "High Knees"],
    attendance: ["1", "3"],
    notes: "Great energy from the group!",
  },
  {
    id: "2",
    courseId: "2",
    date: "2025-01-16",
    time: "7:00 AM",
    exercises: ["Sun Salutation", "Warrior Poses", "Tree Pose", "Savasana"],
    attendance: ["1", "3"],
    notes: "Focus on breathing techniques",
  },
  {
    id: "3",
    courseId: "1",
    date: "2025-01-22",
    time: "6:00 PM",
    exercises: ["Tabata Sprints", "Box Jumps", "Kettlebell Swings"],
    attendance: ["1", "3"],
    notes: "Intense intervals — Sarah kept perfect form and finished strong.",
  },
  {
    id: "4",
    courseId: "3",
    date: "2025-01-20",
    time: "5:00 PM",
    exercises: ["Deadlifts", "Squats", "Romanian Deadlifts"],
    attendance: ["1", "3"],
    notes: "Strength session — Sarah increased her working weight by 5kg on deadlifts.",
  },
  {
    id: "5",
    courseId: "1",
    date: "2025-01-29",
    time: "6:00 PM",
    exercises: ["AMRAP", "Jump Rope", "Push-ups"],
    attendance: ["3"],
    notes: "Drop-in session with new attendees.",
  },
]

export const mockEnrollments = [
  {
    id: "1",
    clientId: "1",
    courseId: "1",
    enrolledAt: "2025-01-01",
    progress: 75,
    sessionsAttended: 10,
    totalSessions: 12,
  },
  {
    id: "2",
    clientId: "1",
    courseId: "2",
    enrolledAt: "2025-01-01",
    progress: 80,
    sessionsAttended: 12,
    totalSessions: 15,
  },
  {
    id: "3",
    clientId: "3",
    courseId: "1",
    enrolledAt: "2025-01-05",
    progress: 50,
    sessionsAttended: 6,
    totalSessions: 12,
  },
]

export const mockProgressRecords = [
  {
    id: "1",
    clientId: "1",
    sessionId: "1",
    courseId: "1",
    date: "2025-01-15",
    performance: 85,
    notes: "Excellent form and endurance",
  },
  {
    id: "2",
    clientId: "1",
    sessionId: "2",
    courseId: "2",
    date: "2025-01-16",
    performance: 90,
    notes: "Great improvement in flexibility",
  },
  {
    id: "3",
    clientId: "1",
    sessionId: "3",
    courseId: "1",
    date: "2025-01-22",
    performance: 88,
    notes: "Strong intervals and excellent pacing",
  },
  {
    id: "4",
    clientId: "1",
    sessionId: "4",
    courseId: "3",
    date: "2025-01-20",
    performance: 92,
    notes: "Major strength gains; increased deadlift working set",
  },
]
